# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cbbd9bee9981d3772a970133950a695e9cc413c871239b2f1540e53ea592cf07da6f2cc697d4aa67cba007f476f2641d3ad5ed4603bcf4dc479060423a1b0e4d

test:
  secret_key_base: e35202e1a4183aeeec83eab2f805661e36e6a1841607dfccbe97b34a26c6e8c2087c3538fc2ea8f67b3da0dbbd2ba579a190056762c93425029e7d58b307f755

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
